# Generated by Django 2.2.10 on 2020-07-19 18:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingtool.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scouter', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data', models.CharField(blank=True, default='', max_length=9999)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('events', models.ManyToManyField(related_name='teams', to='scoutingtool.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scouter', models.CharField(blank=True, max_length=20)),
                ('initiationLine', models.BooleanField()),
                ('onePointMadeTele', models.PositiveIntegerField(default=0)),
                ('onePointMissedTele', models.PositiveIntegerField(default=0)),
                ('twoPointMadeTele', models.PositiveIntegerField(default=0)),
                ('twoPointMissedTele', models.PositiveIntegerField(default=0)),
                ('wheelTurn', models.BooleanField()),
                ('wheelColor', models.BooleanField()),
                ('climb', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('climbAssist', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('balanceResponsibility', models.BooleanField(default=False)),
                ('onePointMadeAuto', models.PositiveIntegerField(default=0)),
                ('onePointMissedAuto', models.PositiveIntegerField(default=0)),
                ('twoPointMadeAuto', models.PositiveIntegerField(default=0)),
                ('twoPointMissedAuto', models.PositiveIntegerField(default=0)),
                ('timeOnDefense', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('bot1Defense', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('bot2Defense', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('bot3Defense', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('timeInoperable', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('connectionIssues', models.BooleanField(default=False)),
                ('mechanicalIssues', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=100000, null=True)),
                ('estimate3pt', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingtool.Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingtool.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches1', to='scoutingtool.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches2', to='scoutingtool.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches3', to='scoutingtool.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches4', to='scoutingtool.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches5', to='scoutingtool.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches6', to='scoutingtool.Team'),
        ),
        migrations.CreateModel(
            name='CurrentScouting',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingtool.Event')),
            ],
        ),
    ]
