# Generated by Django 3.0.3 on 2020-02-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingtool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='code',
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
