# Generated by Django 3.0.3 on 2020-02-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentScouting',
            fields=[
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scoutingtool.Event')),
            ],
        ),
    ]
