# Generated by Django 3.0.2 on 2020-02-04 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingtool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='balanceResponsibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='bot1Defense',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='report',
            name='bot2Defense',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='report',
            name='bot3Defense',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='report',
            name='climb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='climbAssist',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='report',
            name='estimate3pt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='initiationLine',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='onePointMadeAuto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='onePointMadeTele',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='onePointMissedAuto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='onePointMissedTele',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='timeInoperable',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='report',
            name='timeOnDefense',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AddField(
            model_name='report',
            name='twoPointMadeAuto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='twoPointMadeTele',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='twoPointMissedAuto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='twoPointMissedTele',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='wheelColor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='wheelTurn',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
