# Generated by Django 3.0.3 on 2020-02-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingtool', '0002_currentscouting'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentscouting',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentscouting',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingtool.Event'),
        ),
    ]
