# Generated by Django 3.0.3 on 2020-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingtool', '0003_auto_20200215_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentscouting',
            name='id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
