# Generated by Django 3.0.2 on 2020-02-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingtool', '0005_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='matches',
            new_name='data',
        ),
    ]
