# Generated by Django 3.0.2 on 2020-03-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingtool', '0006_auto_20200229_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='connectionIssues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='mechanicalIssues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='park',
            field=models.BooleanField(default=False),
        ),
    ]
